libGraphite/rsrc/rez.cpp

Original code is available at https://github.com/andrews05/kestrel-development-kit/blob/fb2b8e699a017c9561ae369fe387cc724df4cfeb/kas/rsrc/file.cpp#L363-L457
I tested this using the following Cron resource definition:
```
declare Cron {
new (#128, "Example Event") {
FirstDate = 01 01 3100;
LastDate = 31 12 3100;
Random = 50%;
Duration = 7;
};
};
```
The resulting Rez file is available [here](https://github.com/TheDiamondProject/Graphite/files/4496009/CronExample.zip); it is read successfully by EVNEW:

Port Rez format writer from old KDK

---

libGraphite/resources/sound.cpp
libGraphite/resources/sound.hpp

Supports `snd ` resources with the options outlined below.
Reading:
* Formats 1 and 2
* Standard, extended or compressed sampled sound data
* 8, 16, 24 or 32 bits per sample (note EV only uses 8 and 16)
* IMA4 compression
* Stereo/multichannel samples (note EV only uses mono)
Writing:
* Format 1
* Standard sampled sound data
* 8 bits per sample
* Mono
Internally, sounds are represented as an array of channels, each of which contains an array of unsigned 32-bit samples. The loaded data is stored in the least significant bytes of the sample, with the sample bit depth indicating the actual size used.
When writing samples of greater than 8 bits, no dithering is performed—only the 8 most significant bits of the sample are written.

Add Nova sound resource support

---

libGraphite/quickdraw/rle.cpp
libGraphite/quickdraw/rle.hpp

Enables encoding of 16-bit `rlëD` resources and provides functions to allow individual frames to be written from graphite surfaces.
Does not currently emit pixel run opcodes, but this is rarely used in Nova sprites and does not make an appreciable difference to total file sizes.
Fixes an issue with parsing pixel run opcodes.

Add RLE encoding support

---

libGraphite/rsrc/file.cpp
libGraphite/rsrc/file.hpp

This PR add an accessor for the types vector on graphite::rsrc::file, to allow enumerating the types.

Add graphite::rsrc::file::types()

---

libGraphite/data/data.cpp

This PR changes the `graphite::data::data::size()` function to only return the full size of the data if both `m_size` and `m_start` are zero. This allows it to correctly handle empty resources. Fixes #5.
(I'm not sure what the need is to have it return the full size of the data like that but it should still work for that purpose).

Handle empty resources

---

libGraphite/rsrc/classic.cpp

This PR adds a check in graphite::rsrc::classic::write for data offsets that exceed the 24-bit maximum, throwing an error if it would be too big.
(There are of course many other limit checks that could be added but this is the most commonly encountered one in practice)

Throw error for offsets that are too big

---

libGraphite/data/reader.cpp
libGraphite/rsrc/extended.cpp

This PR fixes two issues with reading the extended format.
1. There was a problem reading 64-bit values (at least on my system) where the bitshifting seemed to be restricted to 32-bit values. I've resolved this with a `static_cast<T>`. (Not sure if this is the best way to fix it)
2. Reading of the second preamble was using read_longs instead of read_quads.

Fixes for reading extended format

---

libGraphite/rsrc/classic.cpp

This PR makes three changes to error checking:
1. When reading a classic resource map, don't fail if file is larger than expected. The Resource Manager will happily read such files.
2. When writing a classic resource map, fail if a resource id is out of bounds. This might happen if trying to convert an extended map with a higher id to a classic map.
3. When writing a classic resource map, fail if the file size would exceed 16MB. For some reason the Resource Manager will not read such files even they technically fit the spec. (The max valid size actually seems to be 2^24-2, though I didn't bother with this oddity and left the check at 2^24-1).

Error checking

---

libGraphite/quickdraw/cicn.cpp

This PR fixes cicn encoding to support pixel widths that aren't a multiple of 8, by ensuring the bitmap/mask data uses a whole number of bytes per row.

Fix cicn encoding for odd widths

---

libGraphite/quickdraw/pict.cpp

This PR fixes decoding RGB/ARGB PICT data. Previously the red and blue channels were swapped.

Fix rgb pict decoding

---

libGraphite/quickdraw/cicn.cpp
libGraphite/quickdraw/pixmap.cpp
libGraphite/quickdraw/pixmap.hpp
libGraphite/quickdraw/ppat.cpp
libGraphite/quickdraw/ppat.hpp

This PR adds support for the Pixel Pattern 'ppat' resource, used by EV Nova for radar interference patterns.
The ppat class is mostly just a copy of the cicn class with masks removed. It also modifies the pixmap class to allow getting/setting the pm_table.
I'll look into adding ppat support to kdl as well...

Add support for ppat resource

---

libGraphite/quickdraw/pict.cpp
libGraphite/quickdraw/pict.hpp

This PR adds an error check if QuickTime data is encountered while parsing a PICT.
For reference, attached is an EV Nova plug-in that contains QuickTime compressed PICTs.
[rEV_Yards.zip](https://github.com/TheDiamondProject/Graphite/files/4985938/rEV_Yards.zip)

Throw error if quicktime data

---

libGraphite/quickdraw/pict.cpp

This PR makes two fixes for pict decoding:
1. Decoding packbits could produce more data than required, e.g. for odd width images. The data will now be trimmed to the correct length.
2. Red channel for ARGB data was not set correctly.
I've attached a test file here. Note two of the picts are in ARGB format and the alpha shows they are mostly transparent. Most other software (including ResEdit) seem to ignore the alpha though. Wondering if we should be doing so too?
[pict test.rsrc.zip](https://github.com/TheDiamondProject/Graphite/files/5140062/pict.test.rsrc.zip)

Fixes for pict decoding

---

libGraphite/quickdraw/clut.cpp

This PR fixes an issue reading PICTs with indexed color tables. It changes the `clut::get` method to defer to `clut::at` if the indexed device flag is set.

Support indexed color tables

---

GraphiteTest/main.cpp
libGraphite/rsrc/extended.cpp
libGraphite/rsrc/file.cpp
libGraphite/rsrc/file.hpp
libGraphite/rsrc/manager.cpp
libGraphite/rsrc/manager.hpp
libGraphite/rsrc/type.cpp
libGraphite/rsrc/type.hpp

The idea of this to add a attribute mechanism to the type containers of extended resource forks, thus allowing multiple occurrences of the same "type" but distinct from each other.
For example:
```
+ 'dësc'
- #128: Test Resource
- #129: Something else
+ 'dësc' [lang=fr]
- #128: Test Resource (French)
+ 'dësc' [lang=de]
- #128: Test Resource (German)
```

Extended Resource Attributes

---

libGraphite/quickdraw/clut.cpp
libGraphite/quickdraw/internal/packbits.cpp

This PR makes a couple of changes to improve performance:
1. Changes packbits runs to a double loop with `push_back` instead of `insert`.
2. Changes clut reader to index the entries by their value when the device flag is not set. This allows instant lookups via `get` rather than having to search for the value. Note this ensures safe values by modding them by the count, which in theory could give incorrect results in some cases, but ImagickMagick appears to be doing it the same way (as best I can tell) so I figure it's okay.
(This is primarily helpful for me when running debug builds, which can be pretty slow at decoding PICTs. 1. may not actually make any difference in production.)

Performance improvements

---

libGraphite/quickdraw/geometry.cpp
libGraphite/quickdraw/internal/packbits.cpp
libGraphite/quickdraw/pict.cpp

This PR makes PICT decoding a little safer by ensuring buffers are allocated with the appropriate size and throwing an exception when the packbits data is invalid.
Fixes crashes caused by PICTs mentioned in #21, though doesn't (yet) decode them successfully.

PICT decoding fixes

---

libGraphite/rsrc/rez.cpp

This PR fixes an odd issue with reading resource names from .rez files. It seems EVNEW is not very tidy when writing resource names and fills the 256-byte padding with 0xCC after the initial null-terminator. Previously, graphite's reader was simply reading 256 bytes and then truncating any nulls from the end, which resulted in bad data. The fix is to read a cstring normally and then move to the correct position afterward.
[edit] Possibly it would be better to change the `read_cstr` to always search from the start rather than the end?

Fix reading rez resource names

---

libGraphite/data/data.hpp
libGraphite/quickdraw/internal/packbits.hpp

Here are a few spots where gcc seems to complain. Version 9.3.0 didn't have any problems for me, but version 10.2.0 had these two.

linux and gcc compatibility

---

.github/actions/build_linux/Dockerfile
.github/actions/build_linux/entrypoint.sh
.github/workflows/build-linux.yml
.github/workflows/build-macos.yml
libGraphite/quickdraw/internal/packbits.cpp

Related to https://github.com/EvocationGames/KestrelEngine/pull/46, this PR adds GitHub Actions workflows for Graphite that builds the project on macOS and Linux. Included in this PR is a commit fixing a missing include that the build caught on Linux.

Add GitHub Actions builds for Linux and macOS

---

libGraphite/quickdraw/internal/surface.cpp
libGraphite/quickdraw/pict.cpp
libGraphite/quickdraw/pict.hpp
libGraphite/quickdraw/pixmap.cpp
libGraphite/quickdraw/pixmap.hpp
libGraphite/quickdraw/ppat.cpp

This PR extends PICT support in a number of ways:
- Adds support for pixmaps with < 8bpp.
- Adds support for v1 PICTs.
- Adds support for bits_rect, bits_region and packbits_region opcodes.
- Adheres to the destination rect to set pixels in the correct location.
[pict-tests.rsrc.zip](https://github.com/TheDiamondProject/Graphite/files/6179340/pict-tests.rsrc.zip)

Extend PICT support

---

libGraphite/quickdraw/pict.cpp

This PR makes a tweak to 16-bit PICT decoding to correct the colour accuracy. It's a very subtle difference but the output is generally a touch brighter now and looks identical to that seen within Nova.

Accurate 16-bit PICT decode

---

libGraphite/rsrc/resource.cpp
libGraphite/rsrc/resource.hpp

The PR adds a function `graphite::rsrc::resource::set_data`, to allow setting a resource's data.

Add resource::set_data

---

libGraphite/data/data.cpp

This PR adds a validation check when creating a data slice from a vector. It prevents a potential crash when reading corrupt data.

Validate bounds of data slice

---

libGraphite/rsrc/classic.cpp
libGraphite/rsrc/extended.cpp

This PR fixes reading classic and extended resource files when the type list is empty.

Fix reading empty map

---

libGraphite/quickdraw/pict.cpp
libGraphite/quickdraw/pict.hpp

This PR adds support for two more PICT opcodes: origin and direct bits regions.

More PICT opcodes

---

libGraphite/quickdraw/clut.cpp
libGraphite/quickdraw/clut.hpp

This PR fixes a change made in #23 that turned out to be incorrect. To keep the performance benefits, it changes the clut entries vector to a map.
I've tested this for both parsing and writing, but are there any concerns you have with doing it this way?

Fix clut indices

---

libGraphite/quickdraw/pict.cpp
libGraphite/quickdraw/pict.hpp

This PR defines a number of additional PICT opcodes, all of which are simply ignored for now. They are generally meaningless anyway, but defining them allows parsing of some picts which would otherwise fail.

More opcodes again

---

libGraphite/quickdraw/pict.cpp

Two changes here:
1. The frame size is set from the rect read in the extended header. This is a hack to allow decoding of some images which are larger than their frames (QuickDraw would normally downscale these). In the instances that I've encountered like this, the images really should be displayed at their native size but for whatever reason the frame size has been set incorrectly.
2. All QuickTime rle data is skipped, not just greyscale. I've added in a safety check to ensure we did actually find some real data, just in case the rle assumption isn't always true (though it is true in all instances I've encountered).

More pict hacks

---

libGraphite/rsrc/classic.cpp

On rare occasion, the second preamble in a resource file may be empty. This PR changes the verification to ignore zero values in the second preamble.
Additionally, it verifies that the first preamble is *not* zero, which would otherwise be successfully parsed with an odd result.
(Fixes #32)

Classic file verification

---

libGraphite/quickdraw/cicn.cpp
libGraphite/quickdraw/ppat.cpp

This PR fixes a small issue where cicns & ppats were limited to 255 colours.

Allow 256 colours in cicn/ppat
